- name: hello playbook
  hosts: local
  connection: local
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello world {{COURSE}} WITH DURATION {{DURATION}} TRAINDED BY {{TRAINER}}"