- name: fliters
  hosts: web
  become: yes
  tasks:
  - name: filters and functions
    ansible.builtin.debug:
      msg: "Hello {{ person | default ('Manikanta') }}"

  - name: convert strings into list
    vars:
      fruits: "apple,orange,banana" #string
    ansinle.builtin.debug:
      msg: "Fruits are : {{ fruits.split(',') }}"