- name: fliters
  hosts: web
  become: yes
  tasks:
  - name: filters and functions
    ansible.builtin.debug:
      msg: "Hello {{ person | default ('Manikanta') }}"

  - name: convert strings into list
    vars:
      fruits: "apple,orange,banana" #string
    ansible.builtin.debug:
      msg: "Fruits are : {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      courses:
        name: ansible
        duration: 120HRS
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "list is {{courses | dict2items}}"